experiment:
  name: lr_s1_n100_f4
  seed: 0
data:
  scenario: S1
  train_samples_per_class: 100
  test_samples_per_class: 500
  n_features: 4
model:
  type: classical
  name: lr
training: {}
evaluation:
  log_gradients: false
