experiment:
  name: lr_s3_n100_f4
  seed: 2
data:
  scenario: S3
  train_samples_per_class: 100
  test_samples_per_class: 500
  n_features: 4
model:
  type: classical
  name: lr
training: {}
evaluation:
  log_gradients: false
