experiment:
  name: mlp_s1_n250_f4
  seed: 2
data:
  scenario: S1
  train_samples_per_class: 250
  test_samples_per_class: 500
  n_features: 4
model:
  type: classical
  name: mlp
training: {}
evaluation:
  log_gradients: false
