experiment:
  name: svm_s3_n250_f4
  seed: 0
data:
  scenario: S3
  train_samples_per_class: 250
  test_samples_per_class: 500
  n_features: 4
model:
  type: classical
  name: svm
training: {}
evaluation:
  log_gradients: false
